version: "3.9"

networks:
  ollama_net:
    external: true

services:
  # nginx:
  #   image: nginx:stable
  #   networks:
  #     - ollama_net
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "8080:8080"
  #   environment:
  #     - TZ=America/Los_Angeles
  #   volumes:
  #     # Nginx config
  #     - /home/midtier/ollama-stack/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
  #     # Nginx html files
  #     - /var/ollama_stack/nginx:/usr/share/nginx/html
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure

  ollama:
    image: harbor.mt-ss.cdcr.ca.gov/ai/ollama-no-models/ollama:latest
    networks:
      - ollama_net
    ports:
      - "11434:11434"
    # OLLAMA_KV_CACHE_TYPE values q4_0, q4_1, q5_0, q5_1, q8_0, f16
      # - HTTP_PROXY=http://agency-proxy.lb.cdcr.ca.gov:8080/
      # - HTTPS_PROXY=http://agency-proxy.lb.cdcr.ca.gov:8080/
      # - NO_PROXY=ollama,10.124.131.251,10.124.130.121,cdcr.ca.gov,*.cdcr.ca.gov,localhost,127.0.0.0/24,10.0.0.0/8,153.48.0.0/16,172.0.0.0/8,192.168.0.0/16 ::1
    environment:
      - OLLAMA_DEBUG=0
      - OLLAMA_FLASH_ATTENTION=true
      - OLLAMA_HOST=0.0.0.0 
      - OLLAMA_KEEP_ALIVE=10m
      - OLLAMA_KV_CACHE_TYPE=q4_0
      - OLLAMA_MAX_LOADED_MODELS=4
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_NUM_THREADS=32
      - OLLAMA_ORIGINS="*"
      - OLLAMA_PORT=11434
      - TZ=America/Los_Angeles
    # This preloads multiple models sets the default model in the first "ollama run" statement
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "/bin/ollama serve & \
         sleep 5 && \
         /bin/ollama pull llama3.2:3b && \
         /bin/ollama pull codellama:7b && \
         /bin/ollama pull mistral:7b && \
         /bin/ollama pull deepseek-r1:8b && \
         /bin/ollama pull llama3.1:8b && \
         /bin/ollama pull qwen3.5:9b && \
         /bin/ollama run llama3.2:3b --keepalive 1440m >/dev/null 2>&1 & \
         /bin/ollama run codellama:7b --keepalive 1440m >/dev/null 2>&1 & \
         /bin/ollama run mistral:7b --keepalive 1440m >/dev/null 2>&1 & \
         /bin/ollama run deepseek-r1:8b --keepalive 1440m >/dev/null 2>&1 & \
         /bin/ollama run llama3.1:8b --keepalive 1440m >/dev/null 2>&1 & \
         /bin/ollama run qwen3.5:9b --keepalive 1440m >/dev/null 2>&1 & \
         wait"
      ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Persist Ollama state
      - /var/ollama_stack/ollama/data:/root/.ollama
      # Persistent models
      - /var/ollama_stack/ollama/models:/root/.ollama/models
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "24.0"
          memory: 96G
        reservations:
          cpus: "16.0"
          memory: 64G

  open-webui:
    image: harbor.mt-ss.cdcr.ca.gov/ai/open-webui/open-webui:latest
    networks:
      - ollama_net
    ports:
      - "80:8080"
      - "8080:8080"
    environment:
      - CORS_ALLOW_HEADERS=Content-Type,Authorization
      - CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOW_ORIGIN=*
      - DEFAULT_MODEL=llama3.2:3b
      - ENABLE_OLLAMA_API=true
      - ENABLE_RAG_WEB_LOADER=false
      - ENABLE_RAG_WEB_SEARCH=false
      - ENABLE_SIGNUP_PASSWORD_CONFIRMATION=true
      - ENABLE_SIGNUP=true
      - ENV=dev
      - GLOBAL_LOG_LEVEL=INFO
      - http_proxy=http://agency-proxy.lb.cdcr.ca.gov:8080/
      - https_proxy=http://agency-proxy.lb.cdcr.ca.gov:8080/
      - no_proxy=ollama,10.124.131.251,10.124.130.121,cdcr.ca.gov,*.cdcr.ca.gov,localhost,127.0.0.0/24,10.0.0.0/8,153.48.0.0/16,172.0.0.0/8,192.168.0.0/16 ::1
      - OLLAMA_BASE_URL=http://ollama:11434
      - RAG_EMBEDDING_ENGINE=
      - RAG_EMBEDDING_MODEL=
      - RAG_RERANKING_MODEL=
      - TZ=America/Los_Angeles
      - USE_EMBEDDING_MODEL_DOCKER=
      - USE_RERANKING_MODEL_DOCKER=
      - WEBUI_NAME=CDCR
      # Performance tuning settings
      - ENABLE_BASE_MODELS_CACHE=true
      - MODELS_CACHE_TTL=300
      - THREAD_POOL_SIZE=42
      - WEBUI_CONCURRENCY="32"      
      - WEBUI_MAX_REQUESTS="2048"
      - WEBUI_TIMEOUT="120"
      - WEBUI_WORKERS="4"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/ollama_stack/open-webui:/app/backend/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "8.0"
          memory: 8G
        reservations:
          cpus: "2.0"
          memory: 4G